import Foundation

enum Genre: String, CaseIterable {
    case relationship = "人間関係"
    case sports = "スポーツ"
    case work = "仕事"
    case study = "勉強"
    case ikuji = "育児"
    case relationship2 = "料理"
    case sports2 = "筋トレ"
    case work2 = "投資"
    case study2 = "部活"
    case ikuji2 = "営業"
    case relationship3 = "人間関係3"
    case sports3 = "スポーツ3"
    case work3 = "仕事3"
    case study3 = "勉強3"
    case ikuji3 = "育児3"
    case relationship4 = "人間関係4"
    case sports4 = "スポーツ4"
    case work4 = "仕事4"
    case study4 = "勉強4"
    case ikuji4 = "育児4"
    case study5 = "勉強5"
    case ikuji5 = "育児5"
    case relationship5 = "人間関係5"
    case sports5 = "スポーツ5"
    case work35 = "仕事5"
    case study6 = "勉強6"
    case ikuji6 = "育児6"
    case relationship6 = "人間関係6"
    case sports6 = "スポーツ6"
    case work6 = "仕事6"
    case study7 = "勉強7"
    case ikuji7 = "育児7"
}
